### ISSUE TITLE
Release latest changes

### ISSUE THREAD

**Issue by am17torres** [marceloboeira/aws-lambda-datadog#1]
Hey @marceloboeira thanks for writing this helper. 

Would you mind releasing your latest changes which I believe will fix the issue I'm seeing.

```
$ yarn list aws-lambda-datadog
yarn list v1.9.4
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ aws-lambda-datadog@0.1.1
✨  Done in 0.79s.
```

I'm getting the following error because I haven't specified any tags
```
Cannot read property 'join' of undefined
2018-10-15T17:45:01.571Z - error: TypeError: Cannot read property 'join' of undefined
    at Object.increment (./node_modules/aws-lambda-datadog/src/index.js:7:73)
```

**Comment by marceloboeira** [comment]
Hello @am17torres. I've not tried to install with yarn. I'll take a look here and fix that. If there is anything obvious in the code let me know.

**Comment by am17torres** [comment]
Thanks for the quick reply!

For what it's worth, I don't think it has anything to do with yarn. When I view the [releases](https://github.com/marceloboeira/aws-lambda-datadog/releases/tag/0.1.1) page it says there were 10 commits to master since the release of 0.1.1

**Comment by marceloboeira** [comment]
@am17torres can you send me a snippet to reproduce the error?

I have pushed the latest commits into a tag. (0.1.2).

The whole package is very simple, I just extracted from some shared code we have on my company. It would be nice to have some JS devs looking at it to abstract properly. 

Feel free to contribute 👍

**Comment by am17torres** [comment]
@marceloboeira  when the version was 0.1.1 this line would throw an error because there was no default value of `[]` for the `tags` param. 

```javascript
metrics.increment('trip.cancelled');
```

As I see things that I'd like to tweak I'll gladly submit PRs

**Comment by marceloboeira** [comment]
okay @am17torres. I'll close this issue for now then! Thanks!
